# Usando uma imagem base Python
FROM python:3.8-slim

# Definindo o diretório de trabalho
WORKDIR /app

# Copiando os arquivos necessários para o container
COPY . /app

# Instalando as dependências
RUN pip install -r requirements.txt

# Expondo a porta
EXPOSE 5000

# Comando para iniciar a aplicação
CMD ["python", "convertapp.py"]
